theme: jekyll-theme-Minimal
title: Iraj Ahangari's Website
description: This is my personal GitHub Pages site where I will share information about entropy, information theory, and more.

# Navigation links
header_pages:
  - index.md
  - about.md
  - blog.md
